ARG FEDORA_BOOTC_BASE_IMAGE=quay.io/fedora/fedora-bootc@sha256:e3eaca476d25a47aec32f15fc5ee939a15a40d2cf163bc722d0a598d33558484
FROM ${FEDORA_BOOTC_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus && \
    restorecon -v /usr/local/bin/nimbus >/dev/null 2>&1 || true
