ARG FEDORA_BOOTC_BASE_IMAGE=quay.io/fedora/fedora-bootc@sha256:5cb3f1ce33bb0663effecf6b278dae5c91a97f4ab0b5dddd8a883ba9a9f6b354
FROM ${FEDORA_BOOTC_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus && \
    ln -fs /usr/local/bin/nimbus /usr/libexec/nimbus/nimbus-container-runner && \
    restorecon -v /usr/local/bin/nimbus /usr/libexec/nimbus/nimbus-container-runner >/dev/null 2>&1 || true
