ARG FEDORA_BOOTC_BASE_IMAGE=quay.io/fedora/fedora-bootc@sha256:3ca807c0d2836ca425031a52dfe7fda69ca55a22c54fa78c068a22f43d6489b6
FROM ${FEDORA_BOOTC_BASE_IMAGE}

RUN --mount=type=bind,source=/build-common.sh,target=/run/build-common.sh,z \
    /run/build-common.sh

COPY nimbus /usr/local/bin/nimbus

RUN chmod 0755 /usr/local/bin/nimbus && \
    restorecon -v /usr/local/bin/nimbus >/dev/null 2>&1 || true
